build:
    image: jetbrainsinfra/golang:1.8.3
    volumes:
        - .:/go/src/github.com/jetbrains-infra/packer-builder-vsphere
    working_dir: /go/src/github.com/jetbrains-infra/packer-builder-vsphere
    command: ./build.sh
